### ISSUE TITLE
Nihilus can't relaunch after crashing for the 2nd time

### ISSUE THREAD

**Issue by anthonymendez** [ChristianKern97/nihilus#3] opened 2020-05-01 15:52 UTC
After testing out ban-list and op-list, I attempted to unban myself. I typed maybe three commands to try and figure it out, but the program crashed. Attempts to reopen failed to get it open. Restarting my computer didn't work either. Bug highlighted in line 36 of the file below.

[2020_1_5_v0_5_notes_AM.txt](https://github.com/ChristianKern97/nihilus/files/4565047/2020_1_5_v0_5_notes_AM.txt)

System Info:
Intel Core i5-7300HQ
16 Gb of DDR3 @ 2400 Mhz
GTX 1050

**Comment by anthonymendez** [comment] 2020-05-01 15:52
Will attempt to reinstallation to see if that would fix the issue.

**Comment by anthonymendez** [comment] 2020-05-01 15:54
Reinstallation does not fix the issue. Can't do any more testing if this doesn't get fixed @ChristianKern97

**Comment by ChristianKern97** [comment] 2020-05-01 15:55
Try deleting AppData/Roaming/Nihilus

**Comment by anthonymendez** [comment] 2020-05-01 15:59
https://pastebin.com/zYJKgWer

**Comment by ChristianKern97** [comment] 2020-05-01 16:01
Seems normal. Can you restart the program after deleting the folder?

**Comment by anthonymendez** [comment] 2020-05-01 16:31
I was able to look through the original server world logs.

When I ban the player "hlep", it causes Nihilus to crash. Attempting to re-open Nihilus fails again. The server is still running the background.

**Comment by ChristianKern97** [comment] 2020-05-01 16:36
I can reproduce the issue by banning "hlep".

I will investigate this further to find the cause for it

**Comment by ChristianKern97** [comment] 2020-05-01 16:39
Ok so the issue is cased by banning any player that was not on the server before.

This will be fixed in the next version.

**Closed** 2020-05-02 10:24 UTC
Labels: bug
